### ISSUE TITLE
`datalad clone` does not seem to work within the binder on datasets stored on GIN

### ISSUE THREAD

**Issue by Remi-Gau** [datalad/datalad-binder#2] opened 2021-09-10 16:22 UTC
I opened a terminal from within binder and the following works fine:

```
datalad clone https://github.com/OpenNeuroDatasets/ds003542.git
```

But trying to clone some public dataset from GIN just hangs for a long time and then gives up after a time out.

```
datalad clone git@gin.g-node.org:/RemiGau/spm_moae_fmriprep.git
```

Tried on this dataset: https://gin.g-node.org/RemiGau/spm_moae_fmriprep

And a couple of other public datasets from my GIN account.

**Comment by jsheunis** [comment] 2021-09-16 09:06
Thanks for the issue, Remi, and sorry for the delay in answering. I think the issue is not GIN but rather cloning via ssh (for which an ssh key would need to be set up). I tested cloning via HTTPS and that worked fine:

```
datalad clone https://gin.g-node.org/RemiGau/spm_moae_fmriprep.git
```

It's also irritating that the ssh cloning just hangs without giving useful information about the error. I tried replicating that (with another dataset) on a binder terminal. Got this response:

```
jovyan@jupyter-datalad-2ddatalad-2dbinder-2dti4z3zqi:~$ datalad clone git@gin.g-node.org:/RemiGau/spm_facerep_raw.git
Clone attempt:   0%|                                                                                                                                                                        | 0.00/1.00 [00:00<?, ? Candidate locations/s]
ssh: connect to host gin.g-node.org port 22: Connection timed out
[ERROR  ] Failed to clone from all attempted sources: ['git@gin.g-node.org:/RemiGau/spm_facerep_raw.git'] [install(/home/jovyan/spm_facerep_raw)]                                                                                         
install(error): /home/jovyan/spm_facerep_raw (dataset) [Failed to clone from all attempted sources: ['git@gin.g-node.org:/RemiGau/spm_facerep_raw.git']]
```

**Comment by Remi-Gau** [comment] 2021-09-17 13:30
oh right!!! 

That makes sense. It's obvious now that you say it. :wink: 

Should I mention something to that regard in the README? I suspect others might stumble on to that issue.

**Comment by Remi-Gau** [comment] 2021-09-17 21:00
hum actually using https sets things up so that git annex is ignored so we can't get anything from that sibling. :cry: 

 ```
datalad install https://gin.g-node.org/RemiGau/spm_moae_fmriprep.git
[INFO   ] scanning for unlocked files (this may take some time)                                                          
[INFO   ] Remote origin not usable by git-annex; setting annex-ignore 
```

**Comment by jsheunis** [comment] 2021-09-24 13:58
@Remi-Gau a short note on the README sounds like a good idea. Ideally we could point to an `FAQ` or description in the handbook, but haven't found something directly applicable yet.

Regarding the `annex-ignore` INFO, I've reproduced that:

```
~ $ datalad clone https://gin.g-node.org/RemiGau/spm_moae_fmriprep.git
[INFO   ] Remote origin not usable by git-annex; setting annex-ignore                                                                                                                                                                     
[INFO   ] https://gin.g-node.org/RemiGau/spm_moae_fmriprep.git/config download failed: Not Found                                                                                                                                          
install(ok): /home/jovyan/spm_moae_fmriprep (dataset)
```
```
~ $ cd spm_moae_fmriprep

~/spm_moae_fmriprep $ less dataset_description.json 
dataset_description.json: No such file or directory

~/spm_moae_fmriprep $ datalad get dataset_description.json 
[ERROR  ] not available; (Note that these git remotes have annex-ignore set: origin) [get(/home/jovyan/spm_moae_fmriprep/dataset_description.json)]                                                                                       
get(error): dataset_description.json (file) [not available; (Note that these git remotes have annex-ignore set: origin)]
```
I'll look into this, thanks.

**Comment by jsheunis** [comment] 2021-09-24 14:16
Looks like an easy fix (although confusing issue): you have to strip the trailing `.git`. See [this issue](https://github.com/datalad/datalad/issues/5144) for more info.

I've tested it on my side and seems to work fine:

```
~ $ datalad clone https://gin.g-node.org/RemiGau/spm_moae_fmriprep
install(ok): /home/jovyan/spm_moae_fmriprep (dataset)                                                                                                                                                                                     

~ $ cd spm_moae_fmriprep/

~/spm_moae_fmriprep $ datalad get dataset_description.json 
get(ok): dataset_description.json (file) [from origin...]  
                                                                                                                                                                               
~/spm_moae_fmriprep $ cat dataset_description.json 
{
    "Name": "fMRIPrep - fMRI PREProcessing workflow",
    "BIDSVersion": "1.1.1",
    "PipelineDescription": {
        "Name": "fMRIPrep",
        "Version": "20.1.2",
        "CodeURL": "https://github.com/poldracklab/fmriprep/archive/20.1.2.tar.gz"
    },
    "CodeURL": "https://github.com/poldracklab/fmriprep",
    "HowToAcknowledge": "Please cite our paper (https://doi.org/10.1038/s41592-018-0235-4), and include the generated citation boilerplate within the Methods section of the text."
}~/spm_moae_fmriprep $
```

**Comment by jsheunis** [comment] 2021-09-24 14:22
And related: https://github.com/datalad/datalad/issues/5353

**Comment by jsheunis** [comment] 2022-03-14 14:59
Closing this since I believe the issue is addressed. @Remi-Gau please reopen if necessary.

**Closed as completed by jsheunis** 2022-03-14 14:59 UTC
